//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./common.css";
import { Suspense } from "react";
import Loading from "./loading";
import Image from "next/image";
import localFont from 'next/font/local';
const jerseyFont = localFont({ src: '../../public/fonts/jersey/JerseyM54-aLX9.ttf' });
const pixelFont = localFont({ src: '../../public/fonts/pixel/PixelEmulator-xq08.ttf' });
/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
                <body>
        {/* Your content */}
          {children}
      </body>
    </html>
  );
}
